export const MOVIE_DATA_DEFAULT_VALUES = {
  Actors: '',
  Awards: '',
  BoxOffice: '',
  Country: '',
  DVD: '',
  Director: '',
  Genre: '',
  Language: '',
  Metascore: '',
  Plot: '',
  Poster: '',
  Production: '',
  Rated: '',
  Ratings: [],
  Released: '',
  Response: '',
  Runtime: '',
  Title: '',
  Type: '',
  Website: '',
  Writer: '',
  Year: '',
  imdbID: '',
  imdbRating: '',
  imdbVotes: '',
};
